import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>WhatsApp Web</title>
				<meta
					name="description"
					content="1-1 Real-time messaging generated by Next"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	)
}
